### ISSUE TITLE
Unable to build aar , How to use this library for wire-android

### ISSUE THREAD

**Issue by Himanshu4003** [wireapp/wire-android-sync-engine#2]
i try following command : 

```` Java
sbt publishM2
````

It show below logs : 

```` java

 Some bintray features depend on this.
java.util.NoSuchElementException: key not found: androidaddonlicense
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:58)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:58)
	at android.FallbackSdkLoader$$anonfun$processPackage$2$$anonfun$apply$25.apply(androidRepo.scala:375)
	at android.FallbackSdkLoader$$anonfun$processPackage$2$$anonfun$apply$25.apply(androidRepo.scala:295)
	at scala.Option.map(Option.scala:145)
	at android.FallbackSdkLoader$$anonfun$processPackage$2.apply(androidRepo.scala:295)
	at android.FallbackSdkLoader$$anonfun$processPackage$2.apply(androidRepo.scala:294)
	at scala.Option.flatMap(Option.scala:170)
	at android.FallbackSdkLoader$.processPackage(androidRepo.scala:294)
	at android.FallbackSdkLoader$$anonfun$18.apply(androidRepo.scala:281)
	at android.FallbackSdkLoader$$anonfun$18.apply(androidRepo.scala:277)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at android.FallbackSdkLoader$.parseLegacyXml(androidRepo.scala:277)
	at android.FallbackSdkLoader$.parseLegacyXml(androidRepo.scala:274)
	at com.android.repository.impl.manager.RemoteRepoLoader.fetchPackages(RemoteRepoLoader.java:148)
	at com.android.repository.impl.manager.RepoManagerImpl$LoadTask.run(RepoManagerImpl.java:488)
	at com.android.repository.api.RepoManager$2.runSyncWithProgress(RepoManager.java:305)
	at com.android.repository.impl.manager.RepoManagerImpl.load(RepoManagerImpl.java:329)
	at com.android.repository.api.RepoManager.loadSynchronously(RepoManager.java:292)
	at android.SdkInstaller$.install(androidRepo.scala:96)
	at android.SdkInstaller$.installPackage(androidRepo.scala:44)
	at android.SdkInstaller$.autoInstallPackage(androidRepo.scala:66)
	at android.SdkInstaller$.autoInstallPackage(androidRepo.scala:52)
	at android.SdkInstaller$$anonfun$sdkMemo$1$$anonfun$apply$9.apply(androidRepo.scala:177)
	at android.SdkInstaller$$anonfun$sdkMemo$1$$anonfun$apply$9.apply(androidRepo.scala:176)
	at android.SdkInstaller$.sdkManager(androidRepo.scala:184)
	at android.Plugin$$anonfun$allPluginSettings$125.apply(rules.scala:760)
	at android.Plugin$$anonfun$allPluginSettings$125.apply(rules.scala:760)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] java.util.NoSuchElementException: key not found: androidaddonlicense
[error] Use 'last' for the full log.

````

I don't want to publish so what's proper way to build

**Comment by zbsz** [comment]
Did you change something in build setup, or did you run it directly in freshly cloned repo?
`publishM2` will publish aar and two other jars to your local Maven repo, it won't publish it publicly.

To only generate `aar` you could use: `sbt zmessaging/android:packageAar`, resulting file will be in `zmessaging/target/android/output/`

**Comment by zbsz** [comment]
@Himanshu4003 Please make sure to have `ANDROID_HOME` environment variable set to android sdk directory. And check if you hava android platform 23 installed in sdk manager. 
Will need to add that in build instructions.

**Comment by Himanshu4003** [comment]
Thanks  i am able to build it successfully .

**Comment by suarezu** [comment]
hi there, I have some problem with using this library with zclient:
1. is **zmessaging/android:packageAar** aforementioned invalid? it succeeds but there is no aar file found in zmessaging/target/android/output/

2. **sbt publishM2** succeeds but zclient with the built aar can build successfully but run in failure:
`
> Task :app:compileProdDebugJavaWithJavac
advice defined in hugo.weaving.internal.Hugo has not been applied [Xlint:adviceDidNotMatch]

> Task :app:compileProdDebugScala FAILED
/Users/bitmain/workspace/android/chatchat/app/src/main/java/com/waz/zclient/paintcode/WireDrawable.scala:24: object returning is not a member of package com.waz.utils
import com.waz.utils.returning
       ^
/Users/bitmain/workspace/android/chatchat/app/src/main/java/com/waz/zclient/paintcode/WireDrawable.scala:67: not found: value returning
  private val bgPaint = returning(new Paint())(_.setColor(backgroundColor))
                        ^
/Users/bitmain/workspace/android/chatchat/app/src/main/java/com/waz/zclient/paintcode/WireDrawable.scala:68: not found: value returning
  private val strokePaint = returning(new Paint(Paint.ANTI_ALIAS_FLAG)){ paint =>
                            ^
/Users/bitmain/workspace/android/chatchat/app/src/main/java/com/waz/zclient/paintcode/WireDrawable.scala:24: Unused import
import com.waz.utils.returning
                     ^
/Users/bitmain/workspace/android/chatchat/app/src/main/scala/com/waz/jobs/PushTokenCheckJob.scala:23: object ZLog is not a member of package com.waz
import com.waz.ZLog.{error, verbose}
               ^
/Users/bitmain/workspace/android/chatchat/app/src/main/scala/com/waz/jobs/PushTokenCheckJob.scala:24: object ZLog is not a member of package com.waz
import com.waz.ZLog.ImplicitTag.implicitLogTag
               ^
/Users/bitmain/workspace/android/chatchat/app/src/main/scala/com/waz/jobs/PushTokenCheckJob.scala:29: object returning is not a member of package com.waz.utils
import com.waz.utils.returning
       ^
/Users/bitmain/workspace/android/chatchat/app/src/main/scala/com/waz/services/fcm/FetchJob.scala:24: object ZLog is not a member of package com.waz
import com.waz.ZLog.ImplicitTag._
               ^
`

**Comment by suarezu** [comment]
![screen shot 2018-11-23 at 17 30 17](https://user-images.githubusercontent.com/11764393/48936336-95cfb700-ef45-11e8-92df-cd78381faf39.png)
